### ISSUE TITLE
take place with scroll

### ISSUE THREAD

**Issue by mobd007** [mrflix/paperfold#3]
can you give me the method of paperfold effect take place with scrolling like this website:
http://www.creaktif.com

**Comment by mrflix** [comment]
Oh wow. Thats a nice effect – chaining the fold effect with scrolling.
To create that effect you have to be able to close folds manually. Therefore I just made the internal step function public. It's called `.percentage()` http://felixniklas.com/paperfold/#methods
You can give it a value between `0` and `1`. `0` is closed, `1` is open. `0.5` would be half open.
This way you can hook it up with the scroll position. Still a lot of work though.

**Comment by mobd007** [comment]
Wow thanks man you are a great Developer :8ball:
